syntax on
set number
color jellybeans

set shiftwidth=2
set softtabstop=2
set expandtab
set autoindent
set nowrap

:set wildmode=full

highlight Fixit ctermbg=darkred guibg=darkred
match Fixit /\%81v.\+/
2match Fixit /\s\+$/

set guifont=Monaco:h13

"Execute command silently then redraw the buffer.
command! -nargs=1 Silently
\ | execute ':silent !'.<q-args>
\ | execute ':redraw!'

map <F1> :Silently tmux send-keys -t dev:0.0 'bundle exec rspec %:p -c \|\| echo -e \\a' Enter<CR>
map <F2> :Silently tmux send-keys -t dev:0.0 'rubocop %:p \|\| echo -e \\a' Enter<CR>
map <F3> :Explore .<CR>
nmap <F4> :CommandT<CR>
map <F5> :vsplit<CR>
map <F6> :split<CR>
nmap <F7> :exec '!ack -ri ' . @0<CR>
nmap <F11> :TagbarToggle<CR>
nmap <F12> :source ~/.vimrc<CR>:filetype detect<CR>:exe ":echo 'vimrc reloaded'"<CR>
map <up> <C-W><Up>
map <down> <C-W><Down>
map <left> <C-W><Left>
map <right> <C-W><Right>
