" Colors
syntax on
set number
color jellybeans
set t_Co=256

" Tabs
set shiftwidth=2
set softtabstop=2
set expandtab
set autoindent
set nowrap

" Better tab matching for paths
:set wildmode=full

highlight Fixit ctermbg=darkred guibg=darkred
match Fixit /\%81v.\+/
2match Fixit /\s\+$/

set guifont=Monaco:h13
set hlsearch
set showmatch
set mouse=a

"Execute command silently then redraw the buffer.
command! -nargs=1 Silently
\ | execute ':silent !'.<q-args>
\ | execute ':redraw!'

let mapleader = "\<Tab>"

" No swp files and such, we're editing files checked in to svn.
set nobackup
set nowb
set noswapfile

"TDD support commands
command! -nargs=0 MarkFileToTest
\ | execute "silent !tmux send-keys -t dev.0 'export FILE_TO_TEST=%:p' Enter"
\ | execute ':redraw!'

command! -nargs=0 RunTest
\ | execute "silent !tmux send-keys -t dev.0 'spec_test' Enter"
\ | execute ':redraw!'

map <Leader>t :MarkFileToTest<CR>

" High use keys
map <F1> :RunTest<CR>
map <F3> :Explore<CR>
nmap <F4> :CommandT<CR>
nmap <F9> :exec '!ack -ri ' . @0<CR>
nmap <F10> :TagbarToggle<CR>
nmap <F11> :source ~/.vimrc<CR>:filetype detect<CR>:exe ":echo 'vimrc reloaded'"<CR>
nmap <F12> :help myprefs<CR>

map <Leader>v :Vexplore<CR>
map <Leader>h :Hexplore<CR>

" Buffer nav
map <C-k> <C-W><Up>
map <C-j> <C-W><Down>
map <C-h> <C-W><Left>
map <C-l> <C-W><Right>
map <Leader>l :b#<CR>
map <Leader>. :bnext<CR>
map <Leader>, :bprevious<CR>
